apiVersion: v1
kind: ConfigMap
metadata:
  name: sku-limits-managed-api-service
data:
  rate_limit: |-
    {
      "RHOAM SERVICE SKU": {
        "unit": "minute",
        "requests_per_unit": 20
      }
    }
